"""Capabilities on disk: capabilities/<app>/<name>/<version>.yaml.

Files rather than a database: a capability is reviewed like code, and a YAML diff
between two versions shows exactly what changed. Versions are immutable; a change
is a new version.
"""

from pathlib import Path

import yaml

from ..models.capability import Capability
from ..settings import CAPABILITIES_DIR

HEADER = ("# Capability artifact. Generated by `ui-automation discover`, reviewed by a person, replayed by\n"
          "# `ui-automation replay` with no LLM. Edit only through a new version.\n")


YAML_LINE_WIDTH = 100


def _version_key(path: Path) -> tuple[int, ...]:
    return tuple(int(x) for x in path.stem.split("."))


class CapabilityStore:
    """Reads and writes capability versions on disk."""

    def __init__(self, root: Path = CAPABILITIES_DIR):
        self.root = root

    def path(self, cap: Capability) -> Path:
        return self.root / cap.app.id / cap.name / f"{cap.version}.yaml"

    def _files(self, name: str | None = None) -> list[Path]:
        pattern = f"*/{name}/*.yaml" if name else "*/*/*.yaml"
        return sorted(self.root.glob(pattern), key=lambda p: (p.parent.name, _version_key(p)))

    def all(self) -> list[Capability]:
        return [self.read(p) for p in self._files()]

    def read(self, path: Path) -> Capability:
        return Capability.model_validate(yaml.safe_load(path.read_text(encoding="utf-8")))

    def load(self, name: str, version: str | None = None) -> Capability:
        files = self._files(name)
        if version:
            files = [p for p in files if p.stem == version]
        if not files:
            raise LookupError(f"no capability {name}" + (f" version {version}" if version else ""))
        return self.read(files[-1])

    def next_version(self, app_id: str, name: str) -> str:
        files = sorted((self.root / app_id / name).glob("*.yaml"), key=_version_key)
        if not files:
            return "1.0.0"
        major, minor, _ = _version_key(files[-1])
        return f"{major}.{minor + 1}.0"

    def save(self, cap: Capability, overwrite: bool = False) -> Path:
        path = self.path(cap)
        if path.exists() and not overwrite:
            raise FileExistsError(f"{path} exists; versions are immutable")
        path.parent.mkdir(parents=True, exist_ok=True)
        body = yaml.safe_dump(cap.model_dump(mode="json", exclude_none=True), sort_keys=False,
                              allow_unicode=True, width=YAML_LINE_WIDTH)
        path.write_text(HEADER + body, encoding="utf-8")
        return path
